### ISSUE TITLE
No solutions

### ISSUE THREAD

**Issue by rnelson** [westappdev/aoc2018#1]
Nobody's solved any!

**Comment by Essler** [comment]
I know! It's a problem!

**Comment by rnelson** [comment]
I don't have [much room to speak](https://github.com/rnelson/adventofcode/tree/master/advent2018/src/main/kotlin/com/github/rnelson/adventofcode/days) as I'm way behind. But at least I've _started_. ;-)

**Comment by xeons** [comment]
I don't technically work for West anymore, but I can still participate.  😃

**Comment by Essler** [comment]
The more the merrier!

Hey, I was going to check out Kotlin this year, too...

**Comment by rnelson** [comment]
There's some code scattered around W's repos that is Kotlin. Or maybe they were all my personal repos. I wonder if those still exist, now that my account is disabled...

**Comment by xeons** [comment]
I don't have access to push to the repo. Are we doing pull requests instead?

**Comment by Essler** [comment]
I re-invited you to the org. Not sure how you fell off. I may have accidentally clicked a thing...

**Comment by Essler** [comment]
Closing since there's code here now! Woo!
